// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2022-08-01T20:46:08.327Z

const awsmobile = {
  aws_cloud_logic_custom: [
    {
      endpoint: "https://t5o5erl9sc.execute-api.eu-central-1.amazonaws.com/d1",
      // endpoint: "https://d3hdjqbifqc4x6.cloudfront.net/d1",
      // endpoint: "https://api.minteeble.com/d1",
      name: "ApiGatewayRestApi",
      region: "eu-central-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "eu-central-1:dc0b427b-b1fb-4507-9840-ee89d6338dfe",
  aws_cognito_region: "eu-central-1",
  aws_project_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_5DHlMs3U4",
  aws_user_pools_web_client_id: "2ids3e46gimdcreksf9494fcm",
};

export default awsmobile;
