// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2022-06-28T11:46:10.508Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://6ntfkqpirk.execute-api.eu-central-1.amazonaws.com/prod1',
            name: 'ApiGatewayRestApi',
            region: 'eu-central-1'
        }
    ],
    aws_cognito_identity_pool_id: 'eu-central-1:6c54e86b-2936-4cfa-91c2-a5aa5d665d35',
    aws_cognito_region: 'eu-central-1',
    aws_project_region: 'eu-central-1',
    aws_user_pools_id: 'eu-central-1_BqlIMGcuL',
    aws_user_pools_web_client_id: '4bfn0lf7j01p0738a79vpsi4r9'
};

export default awsmobile;
