// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2022-08-01T20:46:08.327Z
import { EnvironmentType, EnvManager } from "../../models/EnvManager";

const awsmobile = {
  aws_cloud_logic_custom: [
    {
      endpoint: "https://5xs4sm4ucg.execute-api.eu-central-1.amazonaws.com/p1",
      name: "ApiGatewayRestApi",
      region: "eu-central-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "eu-central-1:9478c1d1-5ea4-466e-9984-59d05f90a249",
  aws_cognito_region: "eu-central-1",
  aws_project_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_8wquChhl7",
  aws_user_pools_web_client_id: "2tek469p9vu06msokrv162961p",
};

export default awsmobile;
